# Site settings
title: DiGirolamo Knows

author: Anthony DiGirolamo
email: "anthony.digirolamo@gmail.com"

description: "“He soon acquired the forlorn look that one sees in vegetarians.” ― Gabriel García Márquez, One Hundred Years of Solitude"

# url: http://anthonydigirolamo.github.com
simple_search: http://google.com/search

# Build settings
markdown: kramdown
permalink: pretty

code_dir: downloads/code
github_user: AnthonyDiGirolamo
twitter_user: anthonysavatar
google_analytics_tracking_id: UA-38580803-1

# include: ["downloads", "images"]
exclude: ["Gemfile", "Gemfile.lock", "vendor"]
