# Site settings
title: DiGirolamo Knows
subtitle: ideas.save! if brain.blank?

author: Anthony DiGirolamo
email: "your-email@domain.com"

description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# url: http://anthonydigirolamo.github.com
simple_search: http://google.com/search

# Build settings
markdown: kramdown
permalink: pretty

code_dir: downloads/code
github_user: AnthonyDiGirolamo
twitter_user: anthonysavatar
google_analytics_tracking_id: UA-38580803-1

# include: ["downloads", "images"]
exclude: ["Gemfile", "Gemfile.lock", "vendor"]

